<b>MACHINE LEARNING LAB ASSIGNMENT 4 : KNN</b> <br>
Submitted By : KAMAL KANDPAL <br>
Reg. No. : 21-27-14 <br>
DATA SCIENCE (APPLIED MATHEMATICS)

### IMPORTING LIBRARIES

In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

### IMPORTING THE DATASET 

In [2]:
dataset  = pd.read_csv('iris.csv')
dataset.head()
x = dataset.iloc[:,:-1].values
print('x(first five training examples) :\n',x[0:5,:])
y = dataset.iloc[:,-1].values
print('y(first five training examples) :\n',y[0:5])

x(first five training examples) :
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
y(first five training examples) :
 ['Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa']


### SPLITTING THE DATASET INTO TRAINING SET AND TEST SET 

In [3]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.30,random_state=2)

### FEATURE SCALING

In [4]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)
# print('x_train(first five training examples) :\n',x_train[0:5,:])
# print('x_test(first five training examples) :\n',x_test[0:5,:])

### 1. TRAINING THE KNN MODEL ON THE TRAINING SET (k=1)

In [5]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=1, metric='minkowski', p=2)
classifier.fit(x_train,y_train)
#The default metric is minkowski, and with p=2 is equivalent to the standard Euclidean metric. 

KNeighborsClassifier(n_neighbors=1)

### PREDICTING THE TEST SET RESULTS

In [6]:
y_pred = classifier.predict(x_test)
print('[y_pred , y_test] : \n')
# print(np.concatenate((y_pred.reshape(len(y_pred),1) , y_test.reshape(len(y_test),1)),1))

[y_pred , y_test] : 



### Accuracy Score and Confusion Matrix

In [7]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(accuracy_score(y_test,y_pred))

print('\nThe correct predictions are along the right diagonal in the confusion matrix,rest are wrong predictions :')
print(confusion_matrix(y_test,y_pred))


0.9555555555555556

The correct predictions are along the right diagonal in the confusion matrix,rest are wrong predictions :
[[16  1  0]
 [ 0 14  1]
 [ 0  0 13]]


### 2. TRAINING THE KNN MODEL ON THE TRAINING SET (k=3)

In [8]:
classifier2 = KNeighborsClassifier(n_neighbors=3, metric='minkowski', p=2)
classifier2.fit(x_train,y_train)
y_pred = classifier2.predict(x_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.9333333333333333
[[16  1  0]
 [ 0 13  2]
 [ 0  0 13]]


### 3. TRAINING THE KNN MODEL ON THE TRAINING SET (k=5)

In [9]:
classifier3 = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
classifier3.fit(x_train,y_train)
y_pred = classifier3.predict(x_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.9333333333333333
[[16  1  0]
 [ 0 13  2]
 [ 0  0 13]]
